- name: update web servers
  gather_facts: false
  hosts: web-servers
  tasks:
    - name: updating pkm 
      tags: 
        - update
      apt: 
        update_cache: true
    - name: install nginx
      tags: 
        - install
      apt:
        name: nginx
        state: latest
    - name: copy index.html from host to target 
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
      tags: 
        - always